// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: paas.service.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GrpcAgentServiceClient is the client API for GrpcAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcAgentServiceClient interface {
	Invoke(ctx context.Context, in *AgentRequest, opts ...grpc.CallOption) (*AgentResponse, error)
}

type grpcAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcAgentServiceClient(cc grpc.ClientConnInterface) GrpcAgentServiceClient {
	return &grpcAgentServiceClient{cc}
}

func (c *grpcAgentServiceClient) Invoke(ctx context.Context, in *AgentRequest, opts ...grpc.CallOption) (*AgentResponse, error) {
	out := new(AgentResponse)
	err := c.cc.Invoke(ctx, "/rpc.GrpcAgentService/invoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcAgentServiceServer is the server API for GrpcAgentService service.
// All implementations must embed UnimplementedGrpcAgentServiceServer
// for forward compatibility
type GrpcAgentServiceServer interface {
	Invoke(context.Context, *AgentRequest) (*AgentResponse, error)
	mustEmbedUnimplementedGrpcAgentServiceServer()
}

// UnimplementedGrpcAgentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGrpcAgentServiceServer struct {
}

func (UnimplementedGrpcAgentServiceServer) Invoke(context.Context, *AgentRequest) (*AgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedGrpcAgentServiceServer) mustEmbedUnimplementedGrpcAgentServiceServer() {}

// UnsafeGrpcAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcAgentServiceServer will
// result in compilation errors.
type UnsafeGrpcAgentServiceServer interface {
	mustEmbedUnimplementedGrpcAgentServiceServer()
}

func RegisterGrpcAgentServiceServer(s grpc.ServiceRegistrar, srv GrpcAgentServiceServer) {
	s.RegisterService(&GrpcAgentService_ServiceDesc, srv)
}

func _GrpcAgentService_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcAgentServiceServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.GrpcAgentService/invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcAgentServiceServer).Invoke(ctx, req.(*AgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GrpcAgentService_ServiceDesc is the grpc.ServiceDesc for GrpcAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrpcAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.GrpcAgentService",
	HandlerType: (*GrpcAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "invoke",
			Handler:    _GrpcAgentService_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paas.service.proto",
}
